version: '3.8'
services:
  db:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata/
    user: "$UID:$GID"
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data